### ISSUE TITLE
Request Tutorial Materials on ServerLess Working Mechanism

### ISSUE THREAD

**Issue by X-jy-liu** [ServerlessLLM/ServerlessLLM#106]
### Prerequisites

- [X] I have searched existing issues and reviewed documentation.

### Problem Description

After attending Dr. Luo Ma's presentation, I would like to know more about the underlying logistics and working principles.

### Proposed Solution

I wondered if there are more materials to introduce the framework and underlying logistics, especially for students like me with less experience. I appreciate any help you can provide.

### Importance

Nice to have

**Comment by future-xy** [comment]
Thank you for your suggestion!

We’re working on a blog post based on the slides from our first meetup to introduce the current architecture of ServerlessLLM. In the meantime, you can check out our [OSDI paper](https://www.usenix.org/conference/osdi24/presentation/fu) for more detailed insights.

**Comment by future-xy** [comment]
Hi!

We’ve published a blog post providing an overview of the ServerlessLLM architecture, by PRs #134 and #140. You can view the latest version [here](https://github.com/ServerlessLLM/ServerlessLLM/blob/main/blogs/serverless-llm-architecture/README.md). Additional articles detailing the application of ServerlessLLM and key submodules are coming soon.

I’ll close this issue for now. If you have any further feedback or questions, please feel free to open a new issue to discuss.

Thanks for your interest!
