### ISSUE TITLE
RuntimeError: Failed to connect to GCS.

### ISSUE THREAD

**Issue by MartinRepo** [ServerlessLLM/ServerlessLLM#107]
### Prerequisites

- [X] I have read the [ServerlessLLM documentation](https://serverlessllm.github.io/).
- [X] I have searched the [Issue Tracker](https://github.com/ServerlessLLM/ServerlessLLM/issues) to ensure this hasn't been reported before.

### System Information

OS: Ubuntu 22.4
Python version: 3.10
GPU: NVIDIA GeForce GTX 1060 (on uni's HPC)

### Problem Description

I try to start the worker node on HPC. However, there reports a strange error (shows as the following picture) which never appears in "Issue Tracker". It said "Failed to connect to GCS." I guess probably I got something wrong, but I cannot figure out it. I will show some details as following.
![error](https://github.com/user-attachments/assets/1f834703-623a-47ea-ba7f-bdfdc13dc698)

### Steps to Reproduce

Here is the shell script for submitting to slurm
```shell
#!/bin/sh
#SBATCH --partition=Teach-Standard
#SBATCH --gres=gpu:2                   # Request 2 GPUs as described in documentation
#SBATCH --cpus-per-task=4              # Request 4 CPU cores
#SBATCH --mem=16G                      # Request 16GB of RAM
#SBATCH --time=01:00:00                # Run time (hh:mm:ss)
#SBATCH --output=output_%j.log         # Standard output and error log

cd /home/s2682783/ServerlessLLM

source ~/.bashrc

conda activate sllm-worker
ray start --address=0.0.0.0:6379 --num-cpus=4 --num-gpus=2 \
--resources='{"worker_node": 1, "worker_id_0": 1}' --block

```

Steps to reproduce:
1. "Install from source", as described on the documentation
2. Start head node on the HPC's login node
3. Submit the above script to HPC's Teaching node

### Expected Behavior

Any helpful suggestions will be appreciated!

### Additional Context

Why start the worker node on HPC?

Firstly, I started it on the login node of HPC, and it works as normal. Then I try to submit a shell script to start "store" on HPC (because this step needs GPU to work).
```shell
#!/bin/sh
#SBATCH --partition=Teach-Standard
#SBATCH --gres=gpu:2                   # Request 2 GPUs
#SBATCH --cpus-per-task=4              # Request 4 CPU cores
#SBATCH --mem=16G                      # Request 16GB of RAM
#SBATCH --time=01:00:00                # Run time (hh:mm:ss)
#SBATCH --output=output_%j.log         # Standard output and error log

cd /home/s2682783/ServerlessLLM

source ~/.bashrc
conda activate sllm-worker
nvidia-smi
sllm-store-server
```
I got an error like "cannot find cuda driver". But ```nvidia-smi``` command works.
![cuda_exists](https://github.com/user-attachments/assets/28ab8961-72a7-4aaa-bbcd-3268cb69bb03)
After that, I supposed that if I start the worker node on HPC could work? Finally, I got the error as described above.

**Comment by xinwei-niu** [comment]
Have you used `nvcc -V` to check whether the version matches?

**Comment by future-xy** [comment]
Hi! Thanks for reporting this!

It looks like the issue occurs because you started the Ray head on the login node (with IP address x.x.x.x), while your Slurm batch job is running on a GPU node (y.y.y.y). As a result, when you use ray start --address=0.0.0.0:6379, the Ray worker tries to connect to y.y.y.y:6379, where no head is listening.

I really appreciate you diving into this! Feel free to reach out on Discord, and we can discuss a solution (which you're welcome to submit as a PR!) for users with Slurm clusters. Thanks!
