### ISSUE TITLE
Colab example

### ISSUE THREAD

**Issue by asda488** [ServerlessLLM/ServerlessLLM#108]
Hello,
After attending the in person talk on Wednesday, there were mentions of an example Colab. As such, I have done some minimal cleaning to the notebook I used to run the quickstart, please find it attached as a minimal example (zipped as GitHub does not allow .ipynb, I was unwilling to create a pull request as it is very rough and most likely not suitable for inclusion in the repository at this point without further work).
A few points of note:
- Attempting to use vLLM as the deployment backend yields a generic 500 error, as well as ray workers dying due to OOM errors, however transformers appears to work.
- There appears to be extremely low vRAM usage, even during inference, I am not sure if this is as intended.

[serverlessllmdraft.zip](https://github.com/user-attachments/files/17437231/serverlessllmdraft.zip)

Thank you again.

**Comment by future-xy** [comment]
Hi! Thanks for working on this, we really appreciate it!

It's completely fine to submit a draft PR if you feel it's not ready yet. I think discussing based on a (draft) PR will be much more convenient for both of us than exchanging zip files—lol.

You can also reach out on [Discord](https://discord.gg/J9vcbNWYCB) if you'd like.

**Comment by asda488** [comment]
Hi, thank you for the quick response, I'll be honest and say I didn't know that draft PRs existed haha, thank you and closing with #111.
