### ISSUE TITLE
Will NPU be supported in the future? Similar to Huawei's 910B?

### ISSUE THREAD

**Issue by ToviHe** [ServerlessLLM/ServerlessLLM#115]
Will NPU be supported in the future? Similar to Huawei's 910B?

**Comment by future-xy** [comment]
Thanks for your interest in ServerlessLLM!  
We’re actively expanding hardware support, but we currently don’t have access to NPUs like the Huawei 910B.  
If you’re interested in contributing support for it (similar to PR #33 for ROCm), we’d be happy to welcome your contribution and proactively merge a feature PR for NPU support.

**Comment by luomai** [comment]
Hi @ToviHe , thanks for your question. ServerlessLLM currently supports vLLM which in principle will support many heterogeneous AI processors. Some of my friends told me that Huawei Ascend 910B shall have support for vLLM. Given this, ServerlessLLM shall in principle easily support this, but we are currently lacking the access to this processor for testing it.
