### ISSUE TITLE
[Feature Request] [Docs] Add Support Matrix for Models in ServerlessLLM

### ISSUE THREAD

**Issue by future-xy** [ServerlessLLM/ServerlessLLM#116]
### Prerequisites

- [x] I have searched existing issues and reviewed documentation.

### Problem Description

To enhance transparency and user experience, ServerlessLLM will introduce a support matrix that lists supported models and their compatibility with different backends (e.g., vLLM), similar to [vLLM’s approach](https://docs.vllm.ai/en/latest/models/supported_models.html).

### Proposed Solution

The table will include:

- Model architecture (e.g., GPT, OPT, LLaMA)
- Specific models (e.g., GPT-2, OPT-1.3B, Llama-3.2-1B)
- Example HuggingFace models with links to repositories
- Backend 1 (e.g., vLLM) with a 'check' mark if supported
- Backend 2, Backend 3, etc., with 'check' marks as new backends are supported

This feature will be implemented in the following steps:

1. [ ] **Update Documentation**: Add the support matrix table to the documentation, listing supported model architectures, models, and backends.
2. [ ] **Create Testing Infrastructure**: Upload a standard test script, a file that tracks a list of supported models, and a corresponding GitHub workflow to automatically verify the models in the list.
3. [ ] **Model Testing and Validation**: Allow contributors to test `sllm` and `sllm-store` with models not in the list. When a model passes the tests, it can be added to the supported model list, and the GitHub workflow will automatically verify it.
4. [ ] **Bug Fixes**: Identify and fix any issues that arise during the testing in Step 3 to ensure robust support for all tested models.

### Importance

Nice to have

**Comment by dalongbao** [comment]
I'd like to work on this
