### ISSUE TITLE
Question about Intallation

### ISSUE THREAD

**Issue by X-jy-liu** [ServerlessLLM/ServerlessLLM#123]
### Prerequisites

- [X] I have read the [ServerlessLLM documentation](https://serverlessllm.github.io/).
- [X] I have searched the [Issue Tracker](https://github.com/ServerlessLLM/ServerlessLLM/issues) to ensure this hasn't been reported before.

### System Information

OS: windows 11, using Ubuntu desktop, downloaded from MS store. Python 3.10, GPU 4070s

### Problem Description

After setting the head and worker nodes, I'm following the QuickStart guide. And encounter this error message:
(sllm-worker) s2644572@DESKTOP-0417LDT:~$ sllm-store-server
Run server...
/home/s2644572/miniconda3/envs/sllm-worker/lib/python3.10/site-packages/sllm_store/sllm_store_server: error while loading shared libraries: libcudart.so.12: cannot open shared object file: No such file or directory

And the folder information is below:
![image](https://github.com/user-attachments/assets/acb464f4-163c-4f20-8e0f-5ccfe2ef4dbc)

Could you help, please? Thank you for your time in advance!

### Steps to Reproduce

Code snippets:
```python

```

Steps to reproduce:
1.conda activate sllm
ray start --head --port=6379 --num-cpus=4 --num-gpus=0 \
--resources='{"control_node": 1}' --block
2.conda activate sllm-worker
ray start --address=0.0.0.0:6379 --num-cpus=4 --num-gpus=2 \
--resources='{"worker_node": 1, "worker_id_0": 1}' --block
3.conda activate sllm-worker
sllm-store-server

### Expected Behavior

$ sllm-store-server
TODO Run server...
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20240720 08:40:59.634253 141776 server.cpp:307] Log directory already exists.
I20240720 08:40:59.671192 141776 checkpoint_store.cpp:46] Number of GPUs: 2
I20240720 08:40:59.671768 141776 checkpoint_store.cpp:48] I/O threads: 4, chunk size: 32MB
I20240720 08:40:59.797175 141776 checkpoint_store.cpp:69] GPU 0 UUID: cef23f2a-71f7-44f3-8246-5ebd870755e7
I20240720 08:40:59.951408 141776 checkpoint_store.cpp:69] GPU 1 UUID: bbd10d20-aed8-4324-8b2e-7b6e54aaca0e
I20240720 08:41:00.759124 141776 pinned_memory_pool.cpp:29] Creating PinnedMemoryPool with 1024 buffers of 33554432 bytes
I20240720 08:41:24.315564 141776 checkpoint_store.cpp:80] Memory pool created with 32GB
I20240720 08:41:24.318261 141776 server.cpp:279] Server listening on 0.0.0.0:8073

### Additional Context

Because I'm using a Windows machine, I just started getting familiar with Linux with the Ubuntu app. I'm not sure if my problem is related to the WSL connection. Also, could the SLLM run on Windows?

Ubuntu App description:

Install a complete Ubuntu terminal environment in minutes with Windows Subsystem for Linux (WSL). Develop cross-platform applications, improve your data science or web development workflows and manage IT infrastructure without leaving Windows.

Key features:
  - Efficient command line utilities including bash, ssh, git, apt, npm, pip and many more
  - Manage Docker containers with improved performance and startup times
  - Leverage GPU acceleration for AI/ML workloads with NVIDIA CUDA
  - A consistent development to deployment workflow when using Ubuntu in the cloud
  - 5 years of security patching with Ubuntu Long Term Support (LTS) releases

Ubuntu currently provides the 24.04.1 LTS release. When new LTS versions are released, Ubuntu can be upgraded once the first point release is available. This can be done from the command line by using:

    sudo do-release-upgrade

Installation tips:
  - Search for "Turn Windows features on or off" in the Windows search bar and ensure that "Windows Subsystem for Linux" is turned on before restarting your machine.
  - To launch, use "ubuntu" on the command-line prompt or Windows Terminal, or click on the Ubuntu tile in the Start Menu.

For more information about Ubuntu WSL and how Canonical supports developers please visit:

https://ubuntu.com/wsl

![image](https://github.com/user-attachments/assets/866461a5-3291-4327-a101-d7c5bee93c2f)

**Comment by SecretSettler** [comment]
Hi,
It appears that CUDA 12 may not be installed correctly, or you might be using an older CUDA version. Could you check your CUDA version and switch to CUDA 12? If the issue continues, please let us know.

**Comment by X-jy-liu** [comment]
Hi,

Thank you for your help. I fixed the CUDA issue above but ran into a new one as below. I'm not sure if this is caused by the wsl connection. Given the configuration of my PC, it should not run out of memory. Any advice is really appreciated, thank you!

![image](https://github.com/user-attachments/assets/d519a1d0-0977-4099-9e15-c32c4c3dcac2)

**Comment by SecretSettler** [comment]
Hi,
Thank you for reporting this issue. It may be due to insufficient memory allocated to WSL, which by default uses half of the system's memory. Could you please run `free -h` to check if you have enough available memory? Our store-server creates a 4GB memory pool by default. If the memory is insufficient, you can either reduce the size of the created memory pool by setting the `--mem_pool_size` or increase WSL's memory allocation by modifying its configuration settings. We recommend choosing the latter option.

Additionally, once you have resolved all issues and successfully run ServerlessLLM on your machine, could you please document an example of your setup process on WSL? This would be highly valuable for Windows users. In your example, please cover steps from installing WSL and Ubuntu, any issues encountered and their solutions, and how you ultimately got ServerlessLLM to operate successfully. Write this example in markdown format and save it under the `examples/` folder, then submit a pull request.

Thank you very much! We look forward to your contribution.

**Comment by X-jy-liu** [comment]
Another issue when deploying models:

When I try to deploy the example facebook model, 
```
(sllm) s2644572@DESKTOP-0417LDT:~$ sllm-cli deploy --model facebook/opt-1.3b
INFO 10-30 22:09:40 deploy.py:160] Deploying model facebook/opt-1.3b.
```
I encounter this error message:
```
INFO 10-30 22:20:19 deploy.py:160] Deploying model facebook/opt-1.3b.
ERROR 10-30 22:26:50 deploy.py:172] Failed to register model. Status code: 500. Response: {"detail":"Cannot register model, please contact the administrator"}
```

The details while fetching the model are below:

![e7e424f587552ffb69824b6636984a8](https://github.com/user-attachments/assets/1427e104-7b95-4db6-be67-7ef005d45b25)


I checked my storage and cude settings below, which looks fine to me. Any direction to further fix this is appreciated. Thank you very much!

![image](https://github.com/user-attachments/assets/9e8d41ef-c687-469f-a36c-8a0c79e6d6da)

**Comment by SecretSettler** [comment]
Hi,

We couldn’t reproduce the error on our end. Could you please verify if you've applied the vllm patch located in `sllm_store/vllm_patch`? If the issue persists, try updating your sllm version. Alternatively, you can run:

```bash
pytest -s sllm_store/tests/python/test_save_vllm_model.py
```

to see if the test passes. Ensure you're in the `ServerlessLLM/` directory when executing this test. If the test fails, please check the error log and share it here.

**Comment by X-jy-liu** [comment]
Thank you for your patience again. I updated the packages and locate the sllm_load.patch file under `/sllm_store/vllm_path`. Still the error message is below:
`(VllmModelDownloader pid=1157) An error occurred while saving the model: [Errno 2] No such file or directory: './models/vllm'`

And below is my error message after running test_save_vllm_model.py, I checked my torch is installed and importable the python terminal. Could you please let me know where to further check? Thank you very much!

![image](https://github.com/user-attachments/assets/194f284f-d210-4ff0-8a9c-5d82eb0290b6)

**Comment by SecretSettler** [comment]
Hi,
Did you run the script file `patch.sh` under the same directory as `sllm_load.path`?

**Comment by SiyangShao** [comment]
Hi,
It seems that the pytest you called is the system's pytest, not inside the environment. Could you try `pip install -r requirements-test.txt` and execute the pytest command again?

**Comment by X-jy-liu** [comment]
Dear both, Thank you for your comment! Now, the pytest can run, and the test passed, as shown below.
![d0aee38ebb591e22569457db2c227d8](https://github.com/user-attachments/assets/ecf1243f-8803-446e-b991-158f7901cea7)

After running the patch.sh file under the same dir as sllm_load.patch. I tried to deploy a model again following your Quickstart Guide. And the result is like below.
![d0983f4b51c4818dc90c50502a407b3](https://github.com/user-attachments/assets/5d856109-40ae-4e91-a12e-da5101fa1cdc)

I'm not sure if the wsl connection stops the

**Comment by future-xy** [comment]
> I'm not sure if the wsl connection stops the storage-aware scheduling as error messages below. I'll keep looking up the WSL connection things. At the same time, I would appreciate any suggestions regarding the deploying issues! Thank you very much!
> 
> ```
> (StoreManager pid=6997) WARNING 11-03 16:36:28 store_manager.py:208] Hardware info not provided. Storage-aware scheduling might not work properly
> (SllmController pid=6966) INFO 11-03 16:36:28 controller.py:73] Starting scheduler
> (StoreManager pid=6997) INFO 11-03 16:36:28 store_manager.py:196] Initializing store manager
> (StoreManager pid=6997) WARNING 11-03 16:36:28 store_manager.py:208] Hardware info not provided. Storage-aware scheduling might not work properly
> ```

It looks like this warning message isn't actually an error and shouldn’t impact the deployment. It’s more of an informational message, so it shouldn’t be causing the issue.

**Comment by SecretSettler** [comment]
Hi, there have been some reported issues with WSL related to creating directories due to permission settings. This is often caused by user configuration and mounting issues. Could you please check if you can successfully create directories in this folder? Alternatively, you can run
```python
import os
os.makedirs("./example")
```
to see whether the `example/` folder is successfully created.

**Comment by future-xy** [comment]
Hi,

I followed the QuickStart on WSL and everything looks good so far. Here are my configurations:

WSL version: 2.3.24.0

Kernel version: 5.15.153.1-2

WSLg version: 1.0.65

MSRDC version: 1.2.5620

Direct3D version: 1.611.1-81528511

DXCore version: 10.0.26100.1-240331-1435.ge-release

Windows version: 10.0.26100.2033

Initially, I tried running with 16GB of memory, but it failed. I then extended it to 28GB with an 8GB swap.

The model deployment works as shown in the following screenshot:
![Screenshot 2024-11-05 193828](https://github.com/user-attachments/assets/dbaa6fbd-ff43-41fd-8de4-57a7302f8e05)

**Comment by X-jy-liu** [comment]
Thank you all for the support. It turns out to be there is a models folder created but it's inaccessible (cannot write or read inside). I deleted it and re-created it. Now, it's all good. I'll write a markdown file to record how it sets all of these up and commit it to the example/ folder. Thank you again!

**Comment by SecretSettler** [comment]
> Thank you all for the support. It turns out to be there is a models folder created but it's inaccessible (cannot write or read inside). I deleted it and re-created it. Now, it's all good. I'll write a markdown file to record how it sets all of these up and commit it to the example/ folder, if that's still the location you prefer. Thank you again!

Hi, we also notice that your machine only contains 1 GPU but you allocated 2 on your worker node. Please restart your worker node by:
```bash
conda activate sllm-worker
ray start --address=0.0.0.0:6379 --num-cpus=4 --num-gpus=1
--resources='{"worker_node": 1, "worker_id_0": 1}' --block
```
