### ISSUE TITLE
question about class method usage

### ISSUE THREAD

**Issue by Heeans** [ServerlessLLM/ServerlessLLM#131]
Hello.
After looking into the source code of ServerlessLLM,
1) I was just wondering where exactly SllmLocalStore(class defined in store_manager.py)'s method name loading_loop is used.
I think to use pinned memory feature is to by modifying pinned_memory_pool in above class.
And I see in loading_loop method of SllmLocalStore class is where the modification takes place, however I don't see any code section that actually uses the method.
Also, I couldn't exactly put my finger on how to used pinned memory from the provided Quickstart Guide.
2) could I maybe get exact time related information when you guys are planning to add "migration" feature to your source code? 

I would appreciate your response in advance.

**Comment by future-xy** [comment]
Hi! Thanks for your questions!

1. We've identified this as a bug in the current code, and we'll address it in the upcoming release.  
2. The Ray-based live-migration feature is planned for release in the open-source repository in November.

Feel free to share any additional questions or feedback!
