### ISSUE TITLE
[docker] 500 error occurred during deploy model phase

### ISSUE THREAD

**Issue by ToviHe** [ServerlessLLM/ServerlessLLM#144]
does not use docker-compose.

step1.Start the ray_head node
```
docker run -d \
  --name ray_head \
  --privileged \
  --env MODEL_FOLDER=${MODEL_FOLDER} \
  --env RAY_NUM_CPUS=8 \
  -p 6379:6379 \
  -p 8343:8343 \
  --network sllm \
  serverlessllm/sllm-serve

```
step2.Start the ray_worker node
```
docker run -d \
  --name ray_worker_0 \
   --privileged \
  --env WORKER_ID=0 \
  --env MODEL_FOLDER=/data/models \
  --network sllm \
  -v /data/models:/models \
  serverlessllm/sllm-serve-worker
```

step3.deploy model on host side
```
export LLM_SERVER_URL=http://127.0.0.1:8343/
sllm-cli deploy --model meta/Meta-Llama-3-8B-Instruct
```

After the request, the ray_head node log is as follows
![image](https://github.com/user-attachments/assets/c9d4bb88-e5b5-4992-a58c-ffa227321490)

It seems that there are fewer logs at the back. I don’t know what causes it. Can you help me take a look?
<img width="744" alt="image" src="https://github.com/user-attachments/assets/bba339ad-21b0-49c7-9e71-050c6ce3bb6d">

**Comment by SiyangShao** [comment]
Hi, does such an error also occur for opt models? We noticed that you are trying to deploy the `meta/Meta-Llama-3-8B-Instruct` model, and downloading such a model from hugging face requires login. This may be the reason why downloading and transferring the model raises an error. Could you try passing the valid hugging face tokens with access rights to `meta/Meta-llama-3-8B-Instruct` to the docker container (i.e., by setting `--env HF_TOKEN=YOUR_TOKEN`) and check whether this error also occurs?

**Comment by luomai** [comment]
@ToviHe  thanks for raising this issue. We actually realized that there are several users interested in using Ascend 910B with sLLM. Would you be interested in working with us to support this chip? We have recently added support for AMD GPUs and the process shall be similar to Ascend, we believe.

**Comment by ToviHe** [comment]
> Hi, does such an error also occur for opt models? We noticed that you are trying to deploy the `meta/Meta-Llama-3-8B-Instruct` model, and downloading such a model from hugging face requires login. This may be the reason why downloading and transferring the model raises an error.
> 
> Could you try passing the valid hugging face tokens with access rights to `meta/Meta-llama-3-8B-Instruct` to the docker container (i.e., by setting `--env HF_TOKEN=YOUR_TOKEN`) and check whether this error also occurs?

In fact, this model is on my local disk. Our environment is offline and we cannot download the model from huggingface.

**Comment by ToviHe** [comment]
> @ToviHe thanks for raising this issue. We actually realized that there are several users interested in using Ascend 910B with sLLM. Would you be interested in working with us to support this chip? We have recently added support for AMD GPUs and the process shall be similar to Ascend, we believe.
> 
> We do not have access to Ascend 910B, so we will rely on the community to work with us to support it.

Sorry, the graphics card used in this issue is V100, and we have not yet started trying to use Ascend 910B to run sLLM.

**Comment by SiyangShao** [comment]
> > Hi, does such an error also occur for opt models? We noticed that you are trying to deploy the `meta/Meta-Llama-3-8B-Instruct` model, and downloading such a model from hugging face requires login. This may be the reason why downloading and transferring the model raises an error.
> > Could you try passing the valid hugging face tokens with access rights to `meta/Meta-llama-3-8B-Instruct` to the docker container (i.e., by setting `--env HF_TOKEN=YOUR_TOKEN`) and check whether this error also occurs?
> 
> In fact, this model is on my local disk. Our environment is offline and we cannot download the model from huggingface.

Did you manually transform the model into our format and save it in the right path under the model folder? If you didn't, I think that maybe the reason. By default, the model downloader for vLLM format will always try to download the model from the internet, which may raise an error since the environment is offline.

**Comment by ToviHe** [comment]
> > > Hi, does such an error also occur for opt models? We noticed that you are trying to deploy the `meta/Meta-Llama-3-8B-Instruct` model, and downloading such a model from hugging face requires login. This may be the reason why downloading and transferring the model raises an error.
> > > Could you try passing the valid hugging face tokens with access rights to `meta/Meta-llama-3-8B-Instruct` to the docker container (i.e., by setting `--env HF_TOKEN=YOUR_TOKEN`) and check whether this error also occurs?
> > 
> > 
> > In fact, this model is on my local disk. Our environment is offline and we cannot download the model from huggingface.
> 
> Did you manually transform the model into our format and save it in the right path under the model folder? If you didn't, I think that maybe the reason. By default, the model downloader for vLLM format will always try to download the model from the internet, which may raise an error since the environment is offline.
> 
> You may also ref to this issue for more details about using local path: #128

thanks for your answer.
According to the tips you gave, we first converted the llama model into the sllm format

```
from sllm_store.transformers import save_model

# Load a model from HuggingFace model hub.
import torch
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained('/models/meta/Meta-llama-3-8B-Instruct', torch_dtype=torch.float16)

# Replace './models' with your local path.
save_model(model, '/models/transformers/meta/Meta-llama-3-8B-Instruct')
```
Then I found that I could register successfully by running the following command
```
sllm-cli deploy --model meta/Meta-llama-3-8B-Instruct --backend transformers
```
But when we called the following command request, the following error occurred. It seems that we are still accessing the Internet environment? In fact, we have models locally

![image](https://github.com/user-attachments/assets/a66288f1-1740-4b4f-a5ce-bbdeafb78ee6)
![image](https://github.com/user-attachments/assets/e92ba993-83dd-4b34-87f9-83dfd6cd78c8)
![image](https://github.com/user-attachments/assets/0e43159c-ba60-4f80-a67b-e2730f0e03c2)

At this time, the log of the ray-worker-0 node is as follows
![image](https://github.com/user-attachments/assets/e9997401-9b81-4b93-a489-9747ff42ee81)

**Comment by ToviHe** [comment]
I also ran it using opt-1.3b and found that the error was the same as above.

I wonder if model_name is used in this code to load the tokenizer? But it can’t be found because my model is under /models/? If it is an online environment, will it be downloaded directly from huggingface?
<img width="987" alt="image" src="https://github.com/user-attachments/assets/a5241206-7918-4ad8-ab32-beca254d67e4">

**Comment by SiyangShao** [comment]
It's not because your model is under `./models/`. Since we didn't manually specify the cache space in this line of code, `AutoTokenizer` will try to load the tokenizer firstly from local huggingface cache (which has nothing since it's inside a docker environment), then try to download the tokenizer from hugging face.

**Comment by ToviHe** [comment]
> Yes, this line of code is to load tokenizer. It's not because your model is under `./models/`. Since we didn't manually specify the cache space in this line of code, `AutoTokenizer` will try to load the tokenizer firstly from local huggingface cache (which has nothing since it's inside a docker environment), then try to download the tokenizer from hugging face.

But it seems that we can only use the offline docker environment now.
Is there any other solution I have for this problem?

**Comment by SiyangShao** [comment]
We didn't realize this issue before. It must be a bug and we have to fix it latter.

Could you temporarily save the tokenizer in the same folder (maybe under `./models`, and change this line of code into load from such a path? I'm also trying that.

**Comment by ToviHe** [comment]
> We didn't realize this issue before. It must be a bug and we have to fix it latter.
> 
> Could you temporarily save the tokenizer in the same folder (maybe under `./models`, and change this line of code into load from such a path? I'm also trying that and will give you a reply in few hours.

Okay, thank you, we will try it

**Comment by SiyangShao** [comment]
> > We didn't realize this issue before. It must be a bug and we have to fix it latter.
> > Could you temporarily save the tokenizer in the same folder (maybe under `./models`, and change this line of code into load from such a path? I'm also trying that and will give you a reply in few hours.
> 
> Okay, thank you, we will try it

Hi, I've created a PR for this. https://github.com/ServerlessLLM/ServerlessLLM/pull/155

Could you check whether this PR could solve your problem?

1. For transformer backend, besides what you have do now, also save the tokenizer in same path with `_tokenizer` suffix. i.e., if you take `facebook/opt-1.3b` and it was saved under `./models/transformers/facebook/opt-1.3b`, the tokenizer should be saved under `./models/transformers/facebook/opt-1.3b_tokenizer`.
2. For vLLM backend, use our script proved to transform the local snapshot into our format. The local snapshot path on usual servers should be like `~/.cache/huggingface/hub/model---name/snapshots/some_snapshot_number`
```
python3 examples/sllm_store/save_vllm_model.py --model_name facebook/opt-1.3b --storage_path $MODEL_PATH/vllm --local_model_path $SNAPSHOT_PATH
```

Please note that all the apis I mentioned here are experimental, and we may change that during the modification of the PR.

**Comment by ToviHe** [comment]
> > > We didn't realize this issue before. It must be a bug and we have to fix it latter.
> > > Could you temporarily save the tokenizer in the same folder (maybe under `./models`, and change this line of code into load from such a path? I'm also trying that and will give you a reply in few hours.
> > 
> > 
> > Okay, thank you, we will try it
> 
> Hi, I've created a PR for this. #155
> 
> Could you check whether this PR could solve your problem?
> 
> 1. For transformer backend, besides what you have do now, also save the tokenizer in same path with `_tokenizer` suffix. i.e., if you take `facebook/opt-1.3b` and it was saved under `./models/transformers/facebook/opt-1.3b`, the tokenizer should be saved under `./models/transformers/facebook/opt-1.3b_tokenizer`.
> 2. For vLLM backend, use our script proved to transform the local snapshot into our format. The local snapshot path on usual servers should be like `~/.cache/huggingface/hub/model---name/snapshots/some_snapshot_number`
> 
> ```
> python3 examples/sllm_store/save_vllm_model.py --model_name facebook/opt-1.3b --storage_path $MODEL_PATH/vllm --local_model_path $SNAPSHOT_PATH
> ```
> 
> Please note that all the apis I mentioned here are experimental, and we may change that during the modification of the PR.

Thank you for your PR.
It seems that there is no problem after changing this way. I tried to use the above method and was able to run the model successfully.
![image](https://github.com/user-attachments/assets/ca2538ac-af77-448f-bced-72d1662eb47e)

**Comment by ToviHe** [comment]
By the way, when will this PR be merged? We hope to use the latest version of the source code to build a mirror for testing.Thanks

**Comment by SiyangShao** [comment]
> By the way, when will this PR be merged? We hope to use the latest version of the source code to build a mirror for testing.Thanks

We plan to merge it in the following days. I'll close this issue after the PR is merged.
