### ISSUE TITLE
[Question]Is there a way to let the model last for a while, not offload immediately after inference?

### ISSUE THREAD

**Issue by dblate** [ServerlessLLM/ServerlessLLM#159]
It seems that when model inference finished, it will offload.
Is there a way to configure that let the model last for a while, if there is no other requests, then offload?

**Comment by future-xy** [comment]
Hi! Thanks for raising this issue—it's an important feature to consider.  

Currently, SLLM doesn't support a "keep-alive" configuration, but implementing it shouldn't be too difficult. This would involve modifying the `auto_scaler` and adding a new field to the `auto_scaler_config`.  

Here are some relevant references in the code:  
https://github.com/ServerlessLLM/ServerlessLLM/blob/4cc56dfad45e5f6a28bce88970b1fad3b6c3cb6d/sllm/serve/routers/roundrobin_router.py#L197
https://github.com/ServerlessLLM/ServerlessLLM/blob/4cc56dfad45e5f6a28bce88970b1fad3b6c3cb6d/sllm/cli/default_config.json#L5-L10

Would you be interested in working on this with us to enhance the auto-scaler?

**Comment by dblate** [comment]
That's funny, I'd like to work on it.
