### ISSUE TITLE
Model response is incomplete

### ISSUE THREAD

**Issue by ToviHe** [ServerlessLLM/ServerlessLLM#160]
I use docker container mode to run sllm-serve and sllm-serve-worker.
After successful startup, I use the following command to publish the model
```
sllm-cli deploy --model meta/Meta-Llama-3-8B-Instruct --backend transformers
```
It was also published successfully, and then I accessed the model service
```
curl http://127.0.0.1:8343/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
        "model": "meta/Meta-Llama-3-8B-Instruct",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "你好?你是什么模型"}
        ]
    }'
```
Then the model responds, but it looks like the response is truncated!
![image](https://github.com/user-attachments/assets/0dd8b8fe-009c-45ea-b218-af8f3be339d3)

There doesn't seem to be anything wrong with it in the request logs
![image](https://github.com/user-attachments/assets/04c33e51-cbf6-4d88-a0d5-c4ce2a72c198)

**Comment by ToviHe** [comment]
As shown in the picture above, I also tried to let the model reply about how to write Python quick sort, but it responded with one sentence, and it seemed that the response content was truncated.

**Comment by SecretSettler** [comment]
Hello,  
Thank you for bringing this issue to our attention. You need to include `max_tokens` as part of your request, as it is currently set to a default value of 10. 
So you should change your request to:
```bash
curl http://127.0.0.1:8343/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
        "model": "meta/Meta-Llama-3-8B-Instruct",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "你好?你是什么模型"}
        ],
        "max_tokens": 256
    }'
```
Feel free to reach out if you encounter any further problems.

**Comment by ToviHe** [comment]
> Hello, Thank you for bringing this issue to our attention. You need to include `max_tokens` as part of your request, as it is currently set to a default value of 10. So you should change your request to:
> 
> ```shell
> curl http://127.0.0.1:8343/v1/chat/completions \
> -H "Content-Type: application/json" \
> -d '{
>         "model": "meta/Meta-Llama-3-8B-Instruct",
>         "messages": [
>             {"role": "system", "content": "You are a helpful assistant."},
>             {"role": "user", "content": "你好?你是什么模型"}
>         ],
>         "max_tokens": 256
>     }'
> ```
> 
> Feel free to reach out if you encounter any further problems.

Thank you. By the way, I would like to ask what other parameters this interface supports, such as whether it supports streaming output? Is there a corresponding interface document?
```
/v1/chat/completions
```

**Comment by SecretSettler** [comment]
> > Hello, Thank you for bringing this issue to our attention. You need to include `max_tokens` as part of your request, as it is currently set to a default value of 10. So you should change your request to:
> > ```shell
> > curl http://127.0.0.1:8343/v1/chat/completions \
> > -H "Content-Type: application/json" \
> > -d '{
> >         "model": "meta/Meta-Llama-3-8B-Instruct",
> >         "messages": [
> >             {"role": "system", "content": "You are a helpful assistant."},
> >             {"role": "user", "content": "你好?你是什么模型"}
> >         ],
> >         "max_tokens": 256
> >     }'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Feel free to reach out if you encounter any further problems.
> 
> Thank you. By the way, I would like to ask what other parameters this interface supports, such as whether it supports streaming output? Is there a corresponding interface document?
> 
> ```
> /v1/chat/completions
> ```

Hi, thank you for your question! For the generation interface, we currently support `model`, `temperature`, `max_tokens`, and `messages`. Additional parameters will be introduced in the future. Community contributions are also welcome if you're interested in getting involved.
