### ISSUE TITLE
[Docs] Delete model deployment after testing.

### ISSUE THREAD

**Issue by future-xy** [ServerlessLLM/ServerlessLLM#17]
**Is your feature request related to a problem? Please describe.**
There is no delete instructions in the [quickstart guide](https://serverlessllm.github.io/docs/stable/getting_started/quickstart) currently. However, this is a feature we already support.

**Describe the solution you'd like**
Add `delete` instructions to examples, wherever appliable.

**Comment by JustinTong0323** [comment]
@future-xy This issue could be closed.
