### ISSUE TITLE
FasterCkpt (Faster Checkpoint) API proposal

### ISSUE THREAD

**Issue by future-xy** [ServerlessLLM/ServerlessLLM#2]
## Description
FasterCkpt is a Python library that supports fast model checkpoint loading from multi-tier storage (i.e., DRAM, SSD, HDD, remote storage) into GPUs.

FasterCkpt has the following functions:
1. Convert a HuggingFace model into a loading-optimized format.
2. Load a loading-optimized model checkpoints into GPUs.

## Usage Examples
1. Convert a HuggingFace model into FasterCkpt format:
 ```python
 from fasterckpt import save_model

 save_model('facebook/opt-1.3b', '/mnt/nvme0n1p1/models')
 ```

 2. Launch a model server in a separate process:
 ```bash
 python fasterckpt_server.py --storage-path /mnt/nvme0n1p1/models
 ```
 or
 ```bash
 fasterckpt_server start --storage-path /mnt/nvme0n1p1/models
 ```

 3. Load the model in your code:
 ```python
 from fasterckpt import load_model

 model = load_model('facebook/opt-1.3b')
 ```

**Comment by luomai** [comment]
Could you explain further about the input parameters to `save_model`?  Do you have requirements for the input and output paths?

**Comment by future-xy** [comment]
This is the current `save_model` definition.
```python
def save_model(model_name, storage_path):
    """
    Args:
        model_name: str
            a name of HuggingFace Transformers model
        storage_path: str
            a local path to save the converted model
    """
    pass
```
