### ISSUE TITLE
模型加载器的 vllm 实现 (model loader implementation for vllm)

### ISSUE THREAD

**Issue by pipul** [ServerlessLLM/ServerlessLLM#26]
我粗略看了一下源码，看起来 vllm 并没有使用论文中定义的模型的格式吗？我看代码用的好像就是 vllm 自带的 sharded_state 格式？

**Comment by future-xy** [comment]
> **Original question in English:** I briefly looked over the source code, and it appears that vllm does not use the model format defined in the paper, right? It seems that the code is using the sharded_state format that comes with vllm, doesn't it?

感谢提问！
我们需要修改 vllm 的代码（目前正在[这里](https://github.com/ServerlessLLM/vllm/pull/1)进行测试），以支持我们的自定义模型格式。同时，我们也在探索其他无需从源代码安装定制版 vllm的方法，从而更简单地与 vllm 集成。

Response in English:
Thanks for your question! We need to modify the vllm code (currently being tested [here](https://github.com/ServerlessLLM/vllm/pull/1)) to support our custom model format. We are also exploring other methods that do not require installing a customized version of vllm from source to simplify integration with vllm.

**Comment by pipul** [comment]
@future-xy What's the status of this patch? Is it working? Can I test it?

**Comment by SiyangShao** [comment]
> @future-xy What's the status of this patch [ServerlessLLM/vllm#1](https://github.com/ServerlessLLM/vllm/pull/1) ? Is it working? Can I test it?

Hi, now the vLLM integration with Serverless LLM are testing in this PR: https://github.com/ServerlessLLM/ServerlessLLM/pull/61. If you want to test it yourself, you may also try that on your local machine.

Technically, we provide a patch file which contains necessary modification of vLLM library (now only tested on vLLM v0.5.0), and you may apply that through the following commands:

```bash
VLLM_PATH=$(python -c "import vllm; import os; print(os.path.dirname(os.path.abspath(vllm.__file__)))")
patch -p2 -d $VLLM_PATH < vllm_patch/sllm_load.patch
```
Afterthat, you may use our fast checkpoint loader through `load_format=serverless_llm`. For detailed usage, you may refer to our code under `serve/model_downloader.py` and `serve/backends/vllm_backend.py`

**Comment by SiyangShao** [comment]
Hi, we have already merged that PR into main. Please feel free to test and contact us if there's any bugs!

**Comment by SiyangShao** [comment]
Hi, since we have already merged the PR, this issue will be closed if there's no further questions.
