### ISSUE TITLE
Live migration API proposal

### ISSUE THREAD

**Issue by future-xy** [ServerlessLLM/ServerlessLLM#4]
## Description
Live migration library supports users to enable migratable inference for LLMs.
This library modifies `generate` method to support the follow features:
1. Token-based inference migration;
2. Preemptable LLM inference.

## Usage examples
1. Using with HuggingFace Transformers
```python
import torch
from transformers import OPTForCausalLM, AutoTokenizer

import live_migration

model_name = "facebook/opt-1.3b"
model = OPTForCausalLM.from_pretrained(model_name)

# Generate text using the model with migratable inference enabled
with live_migration.enabled(): 
  # In this context manager, the generation process 
    # 1. records intermediate tokens; 
    # 2. can be migrated seamlessly to another server.
  output = model.generate(input_ids, max_length=50)

...
```

**Comment by luomai** [comment]
How to migrate the `output`?

**Comment by future-xy** [comment]
The current API is designed for users to enable live migration during inference; while the implementation details of live migration, including two-stage migration and those error handling cases, are held in the modified `model.generate` function.

**Comment by luomai** [comment]
In that case, we need to make this semantics in the comments in this sample code. The current way that the comments are written suggests that the migration of intermediate tokens needs to be handled by developers.

Maybe you could make the live migration option explicit for the user like:

`output = model.generate(..., auto_migration=True)`

**Comment by future-xy** [comment]
We propose to use context managers (e.g., `with live_migration.enabled()`) to let users explicitly enable live migration instead of providing modified `generate` functions directly. This could be easy to integrate with different LLM inference frameworks considering that they may provide various `generate` functions.

**Comment by luomai** [comment]
This looks good to me.

**Comment by luomai** [comment]
What is the scope with this `with` statement
