### ISSUE TITLE
Some advice on the quickstart guide

### ISSUE THREAD

**Issue by JasonZhang517** [ServerlessLLM/ServerlessLLM#40]
1. There is some inconsistent in the docker starting part, output and instructions do not match
![image](https://github.com/user-attachments/assets/bf5405e1-edef-4019-b734-c1a6f4b445dc)
2. May indicate explicitly of where users should start a new terminal
3. May use smaller models to reduce the model downloading time.

**Comment by future-xy** [comment]
Hi! Thanks for the feedback!

1 and 2 will be fixed soon.

About 3, this is a very good point. Are you willing to help us test with smaller models and submit a pr to improve this? Thanks!

**Comment by JustinTong0323** [comment]
> 2. May indicate explicitly of where users should start a new terminal
> 
Hi, thanks for pointing out these issues. For advice 2: As in quickstart guide we only work on one machine, so could you please clarify what is the meaning of **where**?

**Comment by JasonZhang517** [comment]
yeah, that is what I mean, once we need to start a new terminal, indicating it will me convenient for users to get clear instructions.
![image](https://github.com/user-attachments/assets/98e4bfdc-2b55-446b-9d92-2276bd751711)
