### ISSUE TITLE
Docs: suggestions for minor improvements

### ISSUE THREAD

**Issue by andrei3131** [ServerlessLLM/ServerlessLLM#48]
On https://serverlessllm.github.io/docs/stable/getting_started/docker_quickstart

- The guide assumes the user has already installed ServerlessLLM CLI, but doesn't provide a link to the installation guide mentioned.
- In Step 5, the expected output shows placeholder timestamps (xx-xx xx:xx:xx), which  could be replaced with actual example timestamps for clarity.

On https://serverlessllm.github.io/docs/stable/getting_started/multi_machine_setup

- assumes the user has already installed ServerlessLLM on all machines, but doesn't provide a direct link to the installation guide mentioned

**Comment by andrei3131** [comment]
- Minor: Pre-requirements -> Pre-requisites (see screenshot)
- There are some TODOs scattered around the docs 
- ServerlessLLM Store docs page has a small formatting issue
- ServerlessLLM CLI page misses description and cli_api and sllm_cli_doc could be renamed for readability; also the short description "ServerlessLLM CLI Documentation" is duplicated for both docs pages
- Remove all caps in Usage Examples TIP -> Tip

Thank you for taking these into consideration.

**Comment by JustinTong0323** [comment]
> The guide assumes the user has already installed ServerlessLLM CLI, but doesn't provide a link to the installation guide mentioned.

For ServerlessLLM CLI, it is directly involved in serverless_llm package, so when user run `pip install .`, the CLI will be installed.

**Comment by JustinTong0323** [comment]
> - Minor: Pre-requirements -> Pre-requisites (see screenshot)
> 
> - There are some TODOs scattered around the docs 
> 
> - ServerlessLLM Store docs page has a small formatting issue
> 
> - ServerlessLLM CLI page misses description and cli_api and sllm_cli_doc could be renamed for readability; also the short description "ServerlessLLM CLI Documentation" is duplicated for both docs pages
> 
> - Remove all caps in Usage Examples TIP -> Tip
> 
> 
> 
> Thank you for taking these into consideration.

Thanks for pointing out these issues, would be fixed soon 👍

**Comment by JustinTong0323** [comment]
> * The guide assumes the user has already installed ServerlessLLM CLI, but doesn't provide a link to the installation guide mentioned.

I think the link is provided, just click the `installation guide` in docker_quickstart page, and it would redirect to the installation guide page. Same for below.

**Comment by andrei3131** [comment]
> > The guide assumes the user has already installed ServerlessLLM CLI, but doesn't provide a link to the installation guide mentioned.
> 
> For ServerlessLLM CLI, it is directly involved in serverless_llm package, so when user run `pip install .`, the CLI will be installed.

Sorry, I might have phrased incorrectly. I meant that the guide is starting abruptly without a reference to the installation. A hyperlink to the installation instructions should suffice.

**Comment by andrei3131** [comment]
> > * ServerlessLLM Store docs page has a small formatting issue
> 
> Could you please specify what kinds of formatting issue in the page? As it looks good on my browser.
> 
> > Remove all caps in Usage Examples TIP -> Tip
> 
> It seems a default text style for the doc package and cannot be changed.

![image](https://github.com/user-attachments/assets/1d8b1461-e35b-454c-8061-155daeda658e)
End quote has an extra space

**Comment by future-xy** [comment]
> > > * ServerlessLLM Store docs page has a small formatting issue
> > 
> > 
> > Could you please specify what kinds of formatting issue in the page? As it looks good on my browser.
> > > Remove all caps in Usage Examples TIP -> Tip
> > 
> > 
> > It seems a default text style for the doc package and cannot be changed.
> 
> ![image](https://private-user-images.githubusercontent.com/15161179/354611805-1d8b1461-e35b-454c-8061-155daeda658e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTc3MjQsIm5iZiI6MTcyMjk5NzQyNCwicGF0aCI6Ii8xNTE2MTE3OS8zNTQ2MTE4MDUtMWQ4YjE0NjEtZTM1Yi00NTRjLTgwNjEtMTU1ZGFlZGE2NThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNzdhMDdjZWJiOTBlZWQyYWUxNWY5Y2NmNjNlNmM2MTA4ZTVkZGQwMDljMmNjOTM1ZjQ4OTM1YmM0MjRhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xxykBG9xUTsH0bWc13kalwmDp0b0_hScpt40X9kj174) End quote has an extra space

Hi Andrei! Could you clarify a bit where is the extra space? This screenshot looks fine to me.

**Comment by andrei3131** [comment]
> > > > * ServerlessLLM Store docs page has a small formatting issue
> > > 
> > > 
> > > Could you please specify what kinds of formatting issue in the page? As it looks good on my browser.
> > > > Remove all caps in Usage Examples TIP -> Tip
> > > 
> > > 
> > > It seems a default text style for the doc package and cannot be changed.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/15161179/354611805-1d8b1461-e35b-454c-8061-155daeda658e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTc3MjQsIm5iZiI6MTcyMjk5NzQyNCwicGF0aCI6Ii8xNTE2MTE3OS8zNTQ2MTE4MDUtMWQ4YjE0NjEtZTM1Yi00NTRjLTgwNjEtMTU1ZGFlZGE2NThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNzdhMDdjZWJiOTBlZWQyYWUxNWY5Y2NmNjNlNmM2MTA4ZTVkZGQwMDljMmNjOTM1ZjQ4OTM1YmM0MjRhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xxykBG9xUTsH0bWc13kalwmDp0b0_hScpt40X9kj174) End quote has an extra space
> 
> Hi Andrei! @andrei3131 Could you clarify a bit where the extra space is? This screenshot looks fine to me.

Hi @future-xy, I am referring specifically to https://serverlessllm.github.io/docs/category/serverlessllm-store, where the back-quoted `sllm-store` is not rendered correctly (it is rendered with the back-tick quotes).

**Comment by future-xy** [comment]
@JustinTong0323 Pls try to change "`sllm-store'" to "<code>sllm-store</code>".
