### ISSUE TITLE
Does ServerlessLLM needs to modify the vLLM to support fast checkpoint loading?

### ISSUE THREAD

**Issue by ConstantineRoot** [ServerlessLLM/ServerlessLLM#57]
ServerlessLLM modifies the model checkpoint loading phase, as far as I know, this involves to modify the vLLM to support such a loading strategy.

After reviewing the codes, I find that current implementation seems not to integrate the fast checkpoint loading into vLLM, so the initialization of vLLM would not take advantages of the fast checkpoint load, is that correct?

https://github.com/ServerlessLLM/ServerlessLLM/blob/bd48b355d2689e25a3b9df808f6955d5766a3e19/serverless_llm/serve/backends/vllm_backend.py#L145

**Comment by SiyangShao** [comment]
Hi, current version of used vLLM will not use our checkpoint load and the integration with vLLM is still under testing. 

For more details about integration with vLLM, you may refer to this issue https://github.com/ServerlessLLM/ServerlessLLM/issues/26. If you want to try it yourself (using fast checkpoint load with vLLM), you may compile the latest `sllm-store` in our main branch (which is under `serverless_llm/store`) and use it with the modified vLLM version https://github.com/ServerlessLLM/vllm/pull/1. The api will keep same with vLLM's `sharded_state` format.

**Comment by SiyangShao** [comment]
Hi, now the vLLM integration with Serverless LLM are testing in this PR: https://github.com/ServerlessLLM/ServerlessLLM/pull/61. If you want to test it yourself, you may also try that on your local machine.

Technically, we provide a patch file which contains necessary modification of vLLM library (now only tested on vLLM v0.5.0), and you may apply that through the following commands:

```bash
VLLM_PATH=$(python -c "import vllm; import os; print(os.path.dirname(os.path.abspath(vllm.__file__)))")
patch -p2 -d $VLLM_PATH < vllm_patch/sllm_load.patch
```
Afterthat, you may use our fast checkpoint loader through `load_format=serverless_llm`. For detailed usage, you may refer to our code under `serve/model_downloader.py` and `serve/backends/vllm_backend.py`

**Comment by SiyangShao** [comment]
Hi, we have already merged that PR into main. Please feel free to test and contact us if there's any bugs!

**Comment by SiyangShao** [comment]
Hi, since we have already merged the PR, this issue will be closed if there's no further questions.
