### ISSUE TITLE
A Question about the Eexperiment

### ISSUE THREAD

**Issue by chenhongyu2048** [ServerlessLLM/ServerlessLLM#7]
In section 7.4, why will the baselines like Ray serve will have such a long latency?
Is this mainly because they need to spend a lot of time downloading models remotely? Is this their natural design?

Thanks for your answer.

**Comment by future-xy** [comment]
Thank you for your question!

In our baseline implementation, designed for optimal performance, we calculate the time required to download model checkpoints assuming a dedicated 10Gbps network connection. Consequently, for the OPT-6.7B model, the download time across all experiments mentioned in section 7.4 is approximately 10 seconds.

The primary cause of high latency in baseline systems is attributed to queuing issues that arise when these systems are unable to process incoming requests efficiently.
